 c_id customers.id%type := &cc_id;
 c_name customerS.Name%type; 



IF c_id <= 0 THEN
 RAISE ex_invalid_id;
 ELSE
 SELECT name, address INTO c_name, c_addr
 FROM customers
 WHERE id = c_id;
 DBMS_OUTPUT.PUT_LINE ('Name: '|| c_name);
 DBMS_OUTPUT.PUT_LINE ('Address: ' || c_addr);
 END IF;

EXCEPTION
 WHEN ex_invalid_id THEN
 dbms_output.put_line('ID must be greater than zero!');
 WHEN no_data_found THEN
 dbms_output.put_line('No such customer!');


CREATE OR REPLACE PROCEDURE GetAllUsers
IS
BEGIN
 SELECT * FROM Users;
END;


NUMBER GENERATED BY DEFAULT AS IDENTITY, first_name

